// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Civo
{
    public static class GetKubernetesVersion
    {
        /// <summary>
        /// Provides access to the available Civo Kubernetes Service versions, with the ability to filter the results.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Civo = Pulumi.Civo;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var stable = Output.Create(Civo.GetKubernetesVersion.InvokeAsync(new Civo.GetKubernetesVersionArgs
        ///         {
        ///             Filters = 
        ///             {
        ///                 new Civo.Inputs.GetKubernetesVersionFilterArgs
        ///                 {
        ///                     Key = "type",
        ///                     Values = 
        ///                     {
        ///                         "stable",
        ///                     },
        ///                 },
        ///             },
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% example %}}
        /// ### Pin a Kubernetes cluster to a specific minor version
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Civo = Pulumi.Civo;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var minorVersion = Output.Create(Civo.GetKubernetesVersion.InvokeAsync(new Civo.GetKubernetesVersionArgs
        ///         {
        ///             Filters = 
        ///             {
        ///                 new Civo.Inputs.GetKubernetesVersionFilterArgs
        ///                 {
        ///                     Key = "version",
        ///                     Values = 
        ///                     {
        ///                         "0.9.1",
        ///                     },
        ///                 },
        ///             },
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetKubernetesVersionResult> InvokeAsync(GetKubernetesVersionArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetKubernetesVersionResult>("civo:index/getKubernetesVersion:getKubernetesVersion", args ?? new GetKubernetesVersionArgs(), options.WithVersion());
    }


    public sealed class GetKubernetesVersionArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetKubernetesVersionFilterArgs>? _filters;

        /// <summary>
        /// Filter the results.
        /// The `filter` block is documented below.
        /// </summary>
        public List<Inputs.GetKubernetesVersionFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetKubernetesVersionFilterArgs>());
            set => _filters = value;
        }

        [Input("sorts")]
        private List<Inputs.GetKubernetesVersionSortArgs>? _sorts;

        /// <summary>
        /// Sort the results.
        /// The `sort` block is documented below.
        /// </summary>
        public List<Inputs.GetKubernetesVersionSortArgs> Sorts
        {
            get => _sorts ?? (_sorts = new List<Inputs.GetKubernetesVersionSortArgs>());
            set => _sorts = value;
        }

        public GetKubernetesVersionArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetKubernetesVersionResult
    {
        public readonly ImmutableArray<Outputs.GetKubernetesVersionFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetKubernetesVersionSortResult> Sorts;
        public readonly ImmutableArray<Outputs.GetKubernetesVersionVersionResult> Versions;

        [OutputConstructor]
        private GetKubernetesVersionResult(
            ImmutableArray<Outputs.GetKubernetesVersionFilterResult> filters,

            string id,

            ImmutableArray<Outputs.GetKubernetesVersionSortResult> sorts,

            ImmutableArray<Outputs.GetKubernetesVersionVersionResult> versions)
        {
            Filters = filters;
            Id = id;
            Sorts = sorts;
            Versions = versions;
        }
    }
}
