// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Civo
{
    public static class GetNetwork
    {
        public static Task<GetNetworkResult> InvokeAsync(GetNetworkArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNetworkResult>("civo:index/getNetwork:getNetwork", args ?? new GetNetworkArgs(), options.WithVersion());
    }


    public sealed class GetNetworkArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("label")]
        public string? Label { get; set; }

        public GetNetworkArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNetworkResult
    {
        public readonly string Cidr;
        public readonly bool Default;
        public readonly string? Id;
        public readonly string? Label;
        public readonly string Name;
        public readonly string Region;

        [OutputConstructor]
        private GetNetworkResult(
            string cidr,

            bool @default,

            string? id,

            string? label,

            string name,

            string region)
        {
            Cidr = cidr;
            Default = @default;
            Id = id;
            Label = label;
            Name = name;
            Region = region;
        }
    }
}
