// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Civo
{
    public static class GetReservedIp
    {
        public static Task<GetReservedIpResult> InvokeAsync(GetReservedIpArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetReservedIpResult>("civo:index/getReservedIp:getReservedIp", args ?? new GetReservedIpArgs(), options.WithDefaults());

        public static Output<GetReservedIpResult> Invoke(GetReservedIpInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetReservedIpResult>("civo:index/getReservedIp:getReservedIp", args ?? new GetReservedIpInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetReservedIpArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetReservedIpArgs()
        {
        }
    }

    public sealed class GetReservedIpInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetReservedIpInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetReservedIpResult
    {
        public readonly string? Id;
        public readonly string InstanceId;
        public readonly string InstanceName;
        public readonly string Ip;
        public readonly string? Name;
        public readonly string Region;

        [OutputConstructor]
        private GetReservedIpResult(
            string? id,

            string instanceId,

            string instanceName,

            string ip,

            string? name,

            string region)
        {
            Id = id;
            InstanceId = instanceId;
            InstanceName = instanceName;
            Ip = ip;
            Name = name;
            Region = region;
        }
    }
}
