// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Civo
{
    public static class GetVolume
    {
        public static Task<GetVolumeResult> InvokeAsync(GetVolumeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetVolumeResult>("civo:index/getVolume:getVolume", args ?? new GetVolumeArgs(), options.WithVersion());
    }


    public sealed class GetVolumeArgs : Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetVolumeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetVolumeResult
    {
        public readonly bool Bootable;
        public readonly string CreatedAt;
        public readonly string? Id;
        public readonly string MountPoint;
        public readonly string? Name;
        public readonly int SizeGb;

        [OutputConstructor]
        private GetVolumeResult(
            bool bootable,

            string createdAt,

            string? id,

            string mountPoint,

            string? name,

            int sizeGb)
        {
            Bootable = bootable;
            CreatedAt = createdAt;
            Id = id;
            MountPoint = mountPoint;
            Name = name;
            SizeGb = sizeGb;
        }
    }
}
