// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDnsDomainRecordResult {
    private final String accountId;
    private final String createdAt;
    private final String domainId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    private final String name;
    private final Integer priority;
    private final Integer ttl;
    private final String type;
    private final String updatedAt;
    private final String value;

    @CustomType.Constructor
    private GetDnsDomainRecordResult(
        @CustomType.Parameter("accountId") String accountId,
        @CustomType.Parameter("createdAt") String createdAt,
        @CustomType.Parameter("domainId") String domainId,
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("name") String name,
        @CustomType.Parameter("priority") Integer priority,
        @CustomType.Parameter("ttl") Integer ttl,
        @CustomType.Parameter("type") String type,
        @CustomType.Parameter("updatedAt") String updatedAt,
        @CustomType.Parameter("value") String value) {
        this.accountId = accountId;
        this.createdAt = createdAt;
        this.domainId = domainId;
        this.id = id;
        this.name = name;
        this.priority = priority;
        this.ttl = ttl;
        this.type = type;
        this.updatedAt = updatedAt;
        this.value = value;
    }

    public String accountId() {
        return this.accountId;
    }
    public String createdAt() {
        return this.createdAt;
    }
    public String domainId() {
        return this.domainId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public Integer priority() {
        return this.priority;
    }
    public Integer ttl() {
        return this.ttl;
    }
    public String type() {
        return this.type;
    }
    public String updatedAt() {
        return this.updatedAt;
    }
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDnsDomainRecordResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String accountId;
        private String createdAt;
        private String domainId;
        private String id;
        private String name;
        private Integer priority;
        private Integer ttl;
        private String type;
        private String updatedAt;
        private String value;

        public Builder() {
    	      // Empty
        }

        public Builder(GetDnsDomainRecordResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.createdAt = defaults.createdAt;
    	      this.domainId = defaults.domainId;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.priority = defaults.priority;
    	      this.ttl = defaults.ttl;
    	      this.type = defaults.type;
    	      this.updatedAt = defaults.updatedAt;
    	      this.value = defaults.value;
        }

        public Builder accountId(String accountId) {
            this.accountId = Objects.requireNonNull(accountId);
            return this;
        }
        public Builder createdAt(String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt);
            return this;
        }
        public Builder domainId(String domainId) {
            this.domainId = Objects.requireNonNull(domainId);
            return this;
        }
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public Builder priority(Integer priority) {
            this.priority = Objects.requireNonNull(priority);
            return this;
        }
        public Builder ttl(Integer ttl) {
            this.ttl = Objects.requireNonNull(ttl);
            return this;
        }
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt);
            return this;
        }
        public Builder value(String value) {
            this.value = Objects.requireNonNull(value);
            return this;
        }        public GetDnsDomainRecordResult build() {
            return new GetDnsDomainRecordResult(accountId, createdAt, domainId, id, name, priority, ttl, type, updatedAt, value);
        }
    }
}
