// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDnsDomainRecordResult {
    /**
     * @return The ID account of the domain
     * 
     */
    private String accountId;
    /**
     * @return The date when it was created in UTC format
     * 
     */
    private String createdAt;
    /**
     * @return The ID of the domain
     * 
     */
    private String domainId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The name of the record
     * 
     */
    private String name;
    /**
     * @return The priority of the record
     * 
     */
    private Integer priority;
    /**
     * @return How long caching DNS servers should cache this record
     * 
     */
    private Integer ttl;
    /**
     * @return The choice of record type from A, CNAME, MX, SRV or TXT
     * 
     */
    private String type;
    /**
     * @return The date when it was updated in UTC format
     * 
     */
    private String updatedAt;
    /**
     * @return The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
     * 
     */
    private String value;

    private GetDnsDomainRecordResult() {}
    /**
     * @return The ID account of the domain
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return The date when it was created in UTC format
     * 
     */
    public String createdAt() {
        return this.createdAt;
    }
    /**
     * @return The ID of the domain
     * 
     */
    public String domainId() {
        return this.domainId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the record
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The priority of the record
     * 
     */
    public Integer priority() {
        return this.priority;
    }
    /**
     * @return How long caching DNS servers should cache this record
     * 
     */
    public Integer ttl() {
        return this.ttl;
    }
    /**
     * @return The choice of record type from A, CNAME, MX, SRV or TXT
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return The date when it was updated in UTC format
     * 
     */
    public String updatedAt() {
        return this.updatedAt;
    }
    /**
     * @return The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
     * 
     */
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDnsDomainRecordResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String createdAt;
        private String domainId;
        private String id;
        private String name;
        private Integer priority;
        private Integer ttl;
        private String type;
        private String updatedAt;
        private String value;
        public Builder() {}
        public Builder(GetDnsDomainRecordResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.createdAt = defaults.createdAt;
    	      this.domainId = defaults.domainId;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.priority = defaults.priority;
    	      this.ttl = defaults.ttl;
    	      this.type = defaults.type;
    	      this.updatedAt = defaults.updatedAt;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            this.accountId = Objects.requireNonNull(accountId);
            return this;
        }
        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt);
            return this;
        }
        @CustomType.Setter
        public Builder domainId(String domainId) {
            this.domainId = Objects.requireNonNull(domainId);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder priority(Integer priority) {
            this.priority = Objects.requireNonNull(priority);
            return this;
        }
        @CustomType.Setter
        public Builder ttl(Integer ttl) {
            this.ttl = Objects.requireNonNull(ttl);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt);
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            this.value = Objects.requireNonNull(value);
            return this;
        }
        public GetDnsDomainRecordResult build() {
            final var _resultValue = new GetDnsDomainRecordResult();
            _resultValue.accountId = accountId;
            _resultValue.createdAt = createdAt;
            _resultValue.domainId = domainId;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.priority = priority;
            _resultValue.ttl = ttl;
            _resultValue.type = type;
            _resultValue.updatedAt = updatedAt;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
