// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package civo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information on an instance for use in other resources. This data source provides all of the instance's properties as configured on your Civo account.
//
// Note: This data source returns a single instance. When specifying a hostname, an error will be raised if more than one instances found.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-civo/sdk/v2/go/civo"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "myhostname.com"
// 		myhostaname, err := civo.LookupInstance(ctx, &GetInstanceArgs{
// 			Hostname: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("instanceOutput", myhostaname.PublicIp)
// 		return nil
// 	})
// }
// ```
func LookupInstance(ctx *pulumi.Context, args *LookupInstanceArgs, opts ...pulumi.InvokeOption) (*LookupInstanceResult, error) {
	var rv LookupInstanceResult
	err := ctx.Invoke("civo:index/getInstance:getInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type LookupInstanceArgs struct {
	// The hostname of the Instance
	Hostname *string `pulumi:"hostname"`
	// The ID of this resource.
	Id *string `pulumi:"id"`
	// The region of an existing Instance
	Region *string `pulumi:"region"`
}

// A collection of values returned by getInstance.
type LookupInstanceResult struct {
	// Total cpu of the inatance
	CpuCores int `pulumi:"cpuCores"`
	// The date of creation of the instance
	CreatedAt string `pulumi:"createdAt"`
	// The size of the disk
	DiskGb int `pulumi:"diskGb"`
	// The ID of the firewall used
	FirewallId string `pulumi:"firewallId"`
	// The hostname of the Instance
	Hostname *string `pulumi:"hostname"`
	// The ID of this resource.
	Id *string `pulumi:"id"`
	// Instance initial password
	InitialPassword string `pulumi:"initialPassword"`
	// The name of the initial user created on the server
	InitialUser string `pulumi:"initialUser"`
	// his will be the ID of the network
	NetworkId string `pulumi:"networkId"`
	// The notes of the instance
	Notes string `pulumi:"notes"`
	// The private IP
	PrivateIp string `pulumi:"privateIp"`
	// Is the ip that is used to route the public ip from the internet to the instance using NAT
	PseudoIp string `pulumi:"pseudoIp"`
	// The public IP
	PublicIp string `pulumi:"publicIp"`
	// Total ram of the instance
	RamMb int `pulumi:"ramMb"`
	// The region of an existing Instance
	Region *string `pulumi:"region"`
	// A fully qualified domain name
	ReverseDns string `pulumi:"reverseDns"`
	// The contents of a script uploaded
	Script string `pulumi:"script"`
	// The name of the size
	Size string `pulumi:"size"`
	// The ID SSH key
	SshkeyId string `pulumi:"sshkeyId"`
	// The status of the instance
	Status string `pulumi:"status"`
	// An optional list of tags
	Tags []string `pulumi:"tags"`
	// The ID for the disk image/template to used to build the instance
	Template string `pulumi:"template"`
}

func LookupInstanceOutput(ctx *pulumi.Context, args LookupInstanceOutputArgs, opts ...pulumi.InvokeOption) LookupInstanceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupInstanceResult, error) {
			args := v.(LookupInstanceArgs)
			r, err := LookupInstance(ctx, &args, opts...)
			return *r, err
		}).(LookupInstanceResultOutput)
}

// A collection of arguments for invoking getInstance.
type LookupInstanceOutputArgs struct {
	// The hostname of the Instance
	Hostname pulumi.StringPtrInput `pulumi:"hostname"`
	// The ID of this resource.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The region of an existing Instance
	Region pulumi.StringPtrInput `pulumi:"region"`
}

func (LookupInstanceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceArgs)(nil)).Elem()
}

// A collection of values returned by getInstance.
type LookupInstanceResultOutput struct{ *pulumi.OutputState }

func (LookupInstanceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceResult)(nil)).Elem()
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutput() LookupInstanceResultOutput {
	return o
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutputWithContext(ctx context.Context) LookupInstanceResultOutput {
	return o
}

// Total cpu of the inatance
func (o LookupInstanceResultOutput) CpuCores() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.CpuCores }).(pulumi.IntOutput)
}

// The date of creation of the instance
func (o LookupInstanceResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The size of the disk
func (o LookupInstanceResultOutput) DiskGb() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.DiskGb }).(pulumi.IntOutput)
}

// The ID of the firewall used
func (o LookupInstanceResultOutput) FirewallId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.FirewallId }).(pulumi.StringOutput)
}

// The hostname of the Instance
func (o LookupInstanceResultOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInstanceResult) *string { return v.Hostname }).(pulumi.StringPtrOutput)
}

// The ID of this resource.
func (o LookupInstanceResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInstanceResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// Instance initial password
func (o LookupInstanceResultOutput) InitialPassword() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.InitialPassword }).(pulumi.StringOutput)
}

// The name of the initial user created on the server
func (o LookupInstanceResultOutput) InitialUser() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.InitialUser }).(pulumi.StringOutput)
}

// his will be the ID of the network
func (o LookupInstanceResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

// The notes of the instance
func (o LookupInstanceResultOutput) Notes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Notes }).(pulumi.StringOutput)
}

// The private IP
func (o LookupInstanceResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

// Is the ip that is used to route the public ip from the internet to the instance using NAT
func (o LookupInstanceResultOutput) PseudoIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.PseudoIp }).(pulumi.StringOutput)
}

// The public IP
func (o LookupInstanceResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

// Total ram of the instance
func (o LookupInstanceResultOutput) RamMb() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceResult) int { return v.RamMb }).(pulumi.IntOutput)
}

// The region of an existing Instance
func (o LookupInstanceResultOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInstanceResult) *string { return v.Region }).(pulumi.StringPtrOutput)
}

// A fully qualified domain name
func (o LookupInstanceResultOutput) ReverseDns() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.ReverseDns }).(pulumi.StringOutput)
}

// The contents of a script uploaded
func (o LookupInstanceResultOutput) Script() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Script }).(pulumi.StringOutput)
}

// The name of the size
func (o LookupInstanceResultOutput) Size() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Size }).(pulumi.StringOutput)
}

// The ID SSH key
func (o LookupInstanceResultOutput) SshkeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.SshkeyId }).(pulumi.StringOutput)
}

// The status of the instance
func (o LookupInstanceResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Status }).(pulumi.StringOutput)
}

// An optional list of tags
func (o LookupInstanceResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The ID for the disk image/template to used to build the instance
func (o LookupInstanceResultOutput) Template() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Template }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInstanceResultOutput{})
}
