// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package civo

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupLoadBalancer(ctx *pulumi.Context, args *LookupLoadBalancerArgs, opts ...pulumi.InvokeOption) (*LookupLoadBalancerResult, error) {
	var rv LookupLoadBalancerResult
	err := ctx.Invoke("civo:index/getLoadBalancer:getLoadBalancer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLoadBalancer.
type LookupLoadBalancerArgs struct {
	Hostname *string `pulumi:"hostname"`
	Id       *string `pulumi:"id"`
}

// A collection of values returned by getLoadBalancer.
type LookupLoadBalancerResult struct {
	Backends                []GetLoadBalancerBackend `pulumi:"backends"`
	FailTimeout             int                      `pulumi:"failTimeout"`
	HealthCheckPath         string                   `pulumi:"healthCheckPath"`
	Hostname                *string                  `pulumi:"hostname"`
	Id                      *string                  `pulumi:"id"`
	IgnoreInvalidBackendTls bool                     `pulumi:"ignoreInvalidBackendTls"`
	MaxConns                int                      `pulumi:"maxConns"`
	MaxRequestSize          int                      `pulumi:"maxRequestSize"`
	Policy                  string                   `pulumi:"policy"`
	Port                    int                      `pulumi:"port"`
	Protocol                string                   `pulumi:"protocol"`
	TlsCertificate          string                   `pulumi:"tlsCertificate"`
	TlsKey                  string                   `pulumi:"tlsKey"`
}
