// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("civo");

/**
 * If region is not set, then no region will be used and them you need expensify in every resource even if you expensify
 * here you can overwrite in a resource.
 */
export let region: string | undefined = __config.get("region");
/**
 * This is the Civo API token. Alternatively, this can also be specified using `CIVO_TOKEN` environment variable.
 */
export let token: string | undefined = __config.get("token");
