// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo;

import com.pulumi.civo.InstanceReservedIpAssignmentArgs;
import com.pulumi.civo.Utilities;
import com.pulumi.civo.inputs.InstanceReservedIpAssignmentState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * The instance reserved ip assignment resource schema definition
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.civo.ReservedIp;
 * import com.pulumi.civo.ReservedIpArgs;
 * import com.pulumi.civo.InstanceReservedIpAssignment;
 * import com.pulumi.civo.InstanceReservedIpAssignmentArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // Send to create a reserved IP
 *         var www = new ReservedIp("www", ReservedIpArgs.builder()        
 *             .name("nginx-www")
 *             .build());
 * 
 *         // We assign the reserved IP to the instance
 *         var webserver_www = new InstanceReservedIpAssignment("webserver-www", InstanceReservedIpAssignmentArgs.builder()        
 *             .instanceId(wwwCivoInstance.id())
 *             .reservedIpId(web_server.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="civo:index/instanceReservedIpAssignment:InstanceReservedIpAssignment")
public class InstanceReservedIpAssignment extends com.pulumi.resources.CustomResource {
    /**
     * The instance id
     * 
     */
    @Export(name="instanceId", refs={String.class}, tree="[0]")
    private Output<String> instanceId;

    /**
     * @return The instance id
     * 
     */
    public Output<String> instanceId() {
        return this.instanceId;
    }
    /**
     * The region of the ip
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return The region of the ip
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * The reserved ip id
     * 
     */
    @Export(name="reservedIpId", refs={String.class}, tree="[0]")
    private Output<String> reservedIpId;

    /**
     * @return The reserved ip id
     * 
     */
    public Output<String> reservedIpId() {
        return this.reservedIpId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public InstanceReservedIpAssignment(String name) {
        this(name, InstanceReservedIpAssignmentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public InstanceReservedIpAssignment(String name, InstanceReservedIpAssignmentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public InstanceReservedIpAssignment(String name, InstanceReservedIpAssignmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("civo:index/instanceReservedIpAssignment:InstanceReservedIpAssignment", name, args == null ? InstanceReservedIpAssignmentArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private InstanceReservedIpAssignment(String name, Output<String> id, @Nullable InstanceReservedIpAssignmentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("civo:index/instanceReservedIpAssignment:InstanceReservedIpAssignment", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static InstanceReservedIpAssignment get(String name, Output<String> id, @Nullable InstanceReservedIpAssignmentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new InstanceReservedIpAssignment(name, id, state, options);
    }
}
