// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDiskImageSort extends com.pulumi.resources.InvokeArgs {

    public static final GetDiskImageSort Empty = new GetDiskImageSort();

    @Import(name="direction")
    private @Nullable String direction;

    public Optional<String> direction() {
        return Optional.ofNullable(this.direction);
    }

    @Import(name="key", required=true)
    private String key;

    public String key() {
        return this.key;
    }

    private GetDiskImageSort() {}

    private GetDiskImageSort(GetDiskImageSort $) {
        this.direction = $.direction;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDiskImageSort defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDiskImageSort $;

        public Builder() {
            $ = new GetDiskImageSort();
        }

        public Builder(GetDiskImageSort defaults) {
            $ = new GetDiskImageSort(Objects.requireNonNull(defaults));
        }

        public Builder direction(@Nullable String direction) {
            $.direction = direction;
            return this;
        }

        public Builder key(String key) {
            $.key = key;
            return this;
        }

        public GetDiskImageSort build() {
            $.key = Objects.requireNonNull($.key, "expected parameter 'key' to be non-null");
            return $;
        }
    }

}
