// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.civo.inputs.GetDiskImageFilterArgs;
import com.pulumi.civo.inputs.GetDiskImageSortArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDiskImageArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDiskImageArgs Empty = new GetDiskImageArgs();

    @Import(name="filters")
    private @Nullable Output<List<GetDiskImageFilterArgs>> filters;

    public Optional<Output<List<GetDiskImageFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    @Import(name="region")
    private @Nullable Output<String> region;

    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    @Import(name="sorts")
    private @Nullable Output<List<GetDiskImageSortArgs>> sorts;

    public Optional<Output<List<GetDiskImageSortArgs>>> sorts() {
        return Optional.ofNullable(this.sorts);
    }

    private GetDiskImageArgs() {}

    private GetDiskImageArgs(GetDiskImageArgs $) {
        this.filters = $.filters;
        this.region = $.region;
        this.sorts = $.sorts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDiskImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDiskImageArgs $;

        public Builder() {
            $ = new GetDiskImageArgs();
        }

        public Builder(GetDiskImageArgs defaults) {
            $ = new GetDiskImageArgs(Objects.requireNonNull(defaults));
        }

        public Builder filters(@Nullable Output<List<GetDiskImageFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        public Builder filters(List<GetDiskImageFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        public Builder filters(GetDiskImageFilterArgs... filters) {
            return filters(List.of(filters));
        }

        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        public Builder region(String region) {
            return region(Output.of(region));
        }

        public Builder sorts(@Nullable Output<List<GetDiskImageSortArgs>> sorts) {
            $.sorts = sorts;
            return this;
        }

        public Builder sorts(List<GetDiskImageSortArgs> sorts) {
            return sorts(Output.of(sorts));
        }

        public Builder sorts(GetDiskImageSortArgs... sorts) {
            return sorts(List.of(sorts));
        }

        public GetDiskImageArgs build() {
            return $;
        }
    }

}
