// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.civo.inputs.GetInstancesSizeFilter;
import com.pulumi.civo.inputs.GetInstancesSizeSort;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetInstancesSizePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetInstancesSizePlainArgs Empty = new GetInstancesSizePlainArgs();

    /**
     * One or more key/value pairs on which to filter results
     * 
     */
    @Import(name="filters")
    private @Nullable List<GetInstancesSizeFilter> filters;

    /**
     * @return One or more key/value pairs on which to filter results
     * 
     */
    public Optional<List<GetInstancesSizeFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * One or more key/direction pairs on which to sort results
     * 
     */
    @Import(name="sorts")
    private @Nullable List<GetInstancesSizeSort> sorts;

    /**
     * @return One or more key/direction pairs on which to sort results
     * 
     */
    public Optional<List<GetInstancesSizeSort>> sorts() {
        return Optional.ofNullable(this.sorts);
    }

    private GetInstancesSizePlainArgs() {}

    private GetInstancesSizePlainArgs(GetInstancesSizePlainArgs $) {
        this.filters = $.filters;
        this.sorts = $.sorts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetInstancesSizePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetInstancesSizePlainArgs $;

        public Builder() {
            $ = new GetInstancesSizePlainArgs();
        }

        public Builder(GetInstancesSizePlainArgs defaults) {
            $ = new GetInstancesSizePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters One or more key/value pairs on which to filter results
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable List<GetInstancesSizeFilter> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters One or more key/value pairs on which to filter results
         * 
         * @return builder
         * 
         */
        public Builder filters(GetInstancesSizeFilter... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param sorts One or more key/direction pairs on which to sort results
         * 
         * @return builder
         * 
         */
        public Builder sorts(@Nullable List<GetInstancesSizeSort> sorts) {
            $.sorts = sorts;
            return this;
        }

        /**
         * @param sorts One or more key/direction pairs on which to sort results
         * 
         * @return builder
         * 
         */
        public Builder sorts(GetInstancesSizeSort... sorts) {
            return sorts(List.of(sorts));
        }

        public GetInstancesSizePlainArgs build() {
            return $;
        }
    }

}
