// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetKubernetesVersionSort extends com.pulumi.resources.InvokeArgs {

    public static final GetKubernetesVersionSort Empty = new GetKubernetesVersionSort();

    /**
     * The sort direction. This may be either `asc` or `desc`.
     * 
     */
    @Import(name="direction")
    private @Nullable String direction;

    /**
     * @return The sort direction. This may be either `asc` or `desc`.
     * 
     */
    public Optional<String> direction() {
        return Optional.ofNullable(this.direction);
    }

    /**
     * Sort versions by this key. This may be one of `default`, `label`, `type`, `version`.
     * 
     */
    @Import(name="key", required=true)
    private String key;

    /**
     * @return Sort versions by this key. This may be one of `default`, `label`, `type`, `version`.
     * 
     */
    public String key() {
        return this.key;
    }

    private GetKubernetesVersionSort() {}

    private GetKubernetesVersionSort(GetKubernetesVersionSort $) {
        this.direction = $.direction;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKubernetesVersionSort defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKubernetesVersionSort $;

        public Builder() {
            $ = new GetKubernetesVersionSort();
        }

        public Builder(GetKubernetesVersionSort defaults) {
            $ = new GetKubernetesVersionSort(Objects.requireNonNull(defaults));
        }

        /**
         * @param direction The sort direction. This may be either `asc` or `desc`.
         * 
         * @return builder
         * 
         */
        public Builder direction(@Nullable String direction) {
            $.direction = direction;
            return this;
        }

        /**
         * @param key Sort versions by this key. This may be one of `default`, `label`, `type`, `version`.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            $.key = key;
            return this;
        }

        public GetKubernetesVersionSort build() {
            $.key = Objects.requireNonNull($.key, "expected parameter 'key' to be non-null");
            return $;
        }
    }

}
