// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.civo.inputs.GetRegionFilter;
import com.pulumi.civo.inputs.GetRegionSort;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRegionPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRegionPlainArgs Empty = new GetRegionPlainArgs();

    /**
     * One or more key/value pairs on which to filter results
     * 
     */
    @Import(name="filters")
    private @Nullable List<GetRegionFilter> filters;

    /**
     * @return One or more key/value pairs on which to filter results
     * 
     */
    public Optional<List<GetRegionFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * One or more key/direction pairs on which to sort results
     * 
     */
    @Import(name="sorts")
    private @Nullable List<GetRegionSort> sorts;

    /**
     * @return One or more key/direction pairs on which to sort results
     * 
     */
    public Optional<List<GetRegionSort>> sorts() {
        return Optional.ofNullable(this.sorts);
    }

    private GetRegionPlainArgs() {}

    private GetRegionPlainArgs(GetRegionPlainArgs $) {
        this.filters = $.filters;
        this.sorts = $.sorts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRegionPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRegionPlainArgs $;

        public Builder() {
            $ = new GetRegionPlainArgs();
        }

        public Builder(GetRegionPlainArgs defaults) {
            $ = new GetRegionPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters One or more key/value pairs on which to filter results
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable List<GetRegionFilter> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters One or more key/value pairs on which to filter results
         * 
         * @return builder
         * 
         */
        public Builder filters(GetRegionFilter... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param sorts One or more key/direction pairs on which to sort results
         * 
         * @return builder
         * 
         */
        public Builder sorts(@Nullable List<GetRegionSort> sorts) {
            $.sorts = sorts;
            return this;
        }

        /**
         * @param sorts One or more key/direction pairs on which to sort results
         * 
         * @return builder
         * 
         */
        public Builder sorts(GetRegionSort... sorts) {
            return sorts(List.of(sorts));
        }

        public GetRegionPlainArgs build() {
            return $;
        }
    }

}
