// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRegionSort extends com.pulumi.resources.InvokeArgs {

    public static final GetRegionSort Empty = new GetRegionSort();

    /**
     * The sort direction. This may be either `asc` or `desc`.
     * 
     */
    @Import(name="direction")
    private @Nullable String direction;

    /**
     * @return The sort direction. This may be either `asc` or `desc`.
     * 
     */
    public Optional<String> direction() {
        return Optional.ofNullable(this.direction);
    }

    /**
     * Sort regions by this key. This may be one of `code`, `country`, `default`, `name`.
     * 
     */
    @Import(name="key", required=true)
    private String key;

    /**
     * @return Sort regions by this key. This may be one of `code`, `country`, `default`, `name`.
     * 
     */
    public String key() {
        return this.key;
    }

    private GetRegionSort() {}

    private GetRegionSort(GetRegionSort $) {
        this.direction = $.direction;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRegionSort defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRegionSort $;

        public Builder() {
            $ = new GetRegionSort();
        }

        public Builder(GetRegionSort defaults) {
            $ = new GetRegionSort(Objects.requireNonNull(defaults));
        }

        /**
         * @param direction The sort direction. This may be either `asc` or `desc`.
         * 
         * @return builder
         * 
         */
        public Builder direction(@Nullable String direction) {
            $.direction = direction;
            return this;
        }

        /**
         * @param key Sort regions by this key. This may be one of `code`, `country`, `default`, `name`.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            $.key = key;
            return this;
        }

        public GetRegionSort build() {
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetRegionSort", "key");
            }
            return $;
        }
    }

}
