// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.civo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KubernetesClusterPoolsArgs extends com.pulumi.resources.ResourceArgs {

    public static final KubernetesClusterPoolsArgs Empty = new KubernetesClusterPoolsArgs();

    @Import(name="instanceNames")
    private @Nullable Output<List<String>> instanceNames;

    public Optional<Output<List<String>>> instanceNames() {
        return Optional.ofNullable(this.instanceNames);
    }

    @Import(name="label")
    private @Nullable Output<String> label;

    public Optional<Output<String>> label() {
        return Optional.ofNullable(this.label);
    }

    @Import(name="nodeCount", required=true)
    private Output<Integer> nodeCount;

    public Output<Integer> nodeCount() {
        return this.nodeCount;
    }

    @Import(name="size", required=true)
    private Output<String> size;

    public Output<String> size() {
        return this.size;
    }

    private KubernetesClusterPoolsArgs() {}

    private KubernetesClusterPoolsArgs(KubernetesClusterPoolsArgs $) {
        this.instanceNames = $.instanceNames;
        this.label = $.label;
        this.nodeCount = $.nodeCount;
        this.size = $.size;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KubernetesClusterPoolsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KubernetesClusterPoolsArgs $;

        public Builder() {
            $ = new KubernetesClusterPoolsArgs();
        }

        public Builder(KubernetesClusterPoolsArgs defaults) {
            $ = new KubernetesClusterPoolsArgs(Objects.requireNonNull(defaults));
        }

        public Builder instanceNames(@Nullable Output<List<String>> instanceNames) {
            $.instanceNames = instanceNames;
            return this;
        }

        public Builder instanceNames(List<String> instanceNames) {
            return instanceNames(Output.of(instanceNames));
        }

        public Builder instanceNames(String... instanceNames) {
            return instanceNames(List.of(instanceNames));
        }

        public Builder label(@Nullable Output<String> label) {
            $.label = label;
            return this;
        }

        public Builder label(String label) {
            return label(Output.of(label));
        }

        public Builder nodeCount(Output<Integer> nodeCount) {
            $.nodeCount = nodeCount;
            return this;
        }

        public Builder nodeCount(Integer nodeCount) {
            return nodeCount(Output.of(nodeCount));
        }

        public Builder size(Output<String> size) {
            $.size = size;
            return this;
        }

        public Builder size(String size) {
            return size(Output.of(size));
        }

        public KubernetesClusterPoolsArgs build() {
            $.nodeCount = Objects.requireNonNull($.nodeCount, "expected parameter 'nodeCount' to be non-null");
            $.size = Objects.requireNonNull($.size, "expected parameter 'size' to be non-null");
            return $;
        }
    }

}
