// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Civo.Inputs
{

    public sealed class KubernetesClusterPoolsGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Nodepool ID
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("instanceNames")]
        private InputList<string>? _instanceNames;

        /// <summary>
        /// Instance names in the nodepool
        /// </summary>
        public InputList<string> InstanceNames
        {
            get => _instanceNames ?? (_instanceNames = new InputList<string>());
            set => _instanceNames = value;
        }

        /// <summary>
        /// Number of nodes in the nodepool
        /// </summary>
        [Input("nodeCount", required: true)]
        public Input<int> NodeCount { get; set; } = null!;

        /// <summary>
        /// Size of the nodes in the nodepool
        /// </summary>
        [Input("size", required: true)]
        public Input<string> Size { get; set; } = null!;

        public KubernetesClusterPoolsGetArgs()
        {
        }
    }
}
