// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Get information on an disk image for use in other resources (e.g. creating a instance) with the ability to filter the results.
 */
export function getDiskImage(args?: GetDiskImageArgs, opts?: pulumi.InvokeOptions): Promise<GetDiskImageResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("civo:index/getDiskImage:getDiskImage", {
        "filters": args.filters,
        "region": args.region,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getDiskImage.
 */
export interface GetDiskImageArgs {
    filters?: inputs.GetDiskImageFilter[];
    region?: string;
    sorts?: inputs.GetDiskImageSort[];
}

/**
 * A collection of values returned by getDiskImage.
 */
export interface GetDiskImageResult {
    readonly diskimages: outputs.GetDiskImageDiskimage[];
    readonly filters?: outputs.GetDiskImageFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly region?: string;
    readonly sorts?: outputs.GetDiskImageSort[];
}

export function getDiskImageOutput(args?: GetDiskImageOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDiskImageResult> {
    return pulumi.output(args).apply(a => getDiskImage(a, opts))
}

/**
 * A collection of arguments for invoking getDiskImage.
 */
export interface GetDiskImageOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetDiskImageFilterArgs>[]>;
    region?: pulumi.Input<string>;
    sorts?: pulumi.Input<pulumi.Input<inputs.GetDiskImageSortArgs>[]>;
}
