// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDnsDomainName(args?: GetDnsDomainNameArgs, opts?: pulumi.InvokeOptions): Promise<GetDnsDomainNameResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("civo:index/getDnsDomainName:getDnsDomainName", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDnsDomainName.
 */
export interface GetDnsDomainNameArgs {
    /**
     * The id of the domain.
     */
    readonly id?: string;
    /**
     * The name of the domain.
     */
    readonly name?: string;
}

/**
 * A collection of values returned by getDnsDomainName.
 */
export interface GetDnsDomainNameResult {
    /**
     * A unique ID that can be used to identify and reference a domain.
     */
    readonly id?: string;
    /**
     * The name of the domain.
     */
    readonly name?: string;
}
