// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getInstance(args?: GetInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetInstanceResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("civo:index/getInstance:getInstance", {
        "hostname": args.hostname,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstance.
 */
export interface GetInstanceArgs {
    /**
     * The hostname of the Instance.
     */
    readonly hostname?: string;
    /**
     * The ID of the Instance
     */
    readonly id?: string;
}

/**
 * A collection of values returned by getInstance.
 */
export interface GetInstanceResult {
    /**
     * Total cpu of the inatance.
     */
    readonly cpuCores: number;
    /**
     * The date of creation of the instance
     */
    readonly createdAt: string;
    /**
     * The size of the disk.
     */
    readonly diskGb: number;
    /**
     * The ID of the firewall used.
     */
    readonly firewallId: string;
    /**
     * The Instance hostname.
     */
    readonly hostname?: string;
    /**
     * The ID of the Instance.
     */
    readonly id?: string;
    /**
     * Instance initial password
     */
    readonly initialPassword: string;
    /**
     * The name of the initial user created on the server.
     */
    readonly initialUser: string;
    /**
     * This will be the ID of the network.
     */
    readonly networkId: string;
    /**
     * The notes of the instance.
     */
    readonly notes: string;
    /**
     * The private ip.
     */
    readonly privateIp: string;
    /**
     * Is the ip that is used to route the public ip from the internet to the instance using NAT
     */
    readonly pseudoIp: string;
    /**
     * The public ip.
     */
    readonly publicIp: string;
    /**
     * Total ram of the instance.
     */
    readonly ramMb: number;
    /**
     * A fully qualified domain name.
     */
    readonly reverseDns: string;
    /**
     * the contents of a script uploaded
     */
    readonly script: string;
    /**
     * The name of the size.
     */
    readonly size: string;
    /**
     * The ID SSH.
     */
    readonly sshkeyId: string;
    /**
     * The status of the instance
     */
    readonly status: string;
    /**
     * An optional list of tags
     */
    readonly tags: string[];
    /**
     * The ID for the template to used to build the instance.
     */
    readonly template: string;
}
