// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getKubernetesCluster(args?: GetKubernetesClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesClusterResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("civo:index/getKubernetesCluster:getKubernetesCluster", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubernetesCluster.
 */
export interface GetKubernetesClusterArgs {
    readonly id?: string;
    readonly name?: string;
}

/**
 * A collection of values returned by getKubernetesCluster.
 */
export interface GetKubernetesClusterResult {
    readonly apiEndpoint: string;
    readonly applications: string;
    readonly builtAt: string;
    readonly createdAt: string;
    readonly dnsEntry: string;
    readonly id?: string;
    readonly installedApplications: outputs.GetKubernetesClusterInstalledApplication[];
    readonly instances: outputs.GetKubernetesClusterInstance[];
    readonly kubeconfig: string;
    readonly kubernetesVersion: string;
    readonly masterIp: string;
    readonly name?: string;
    readonly numTargetNodes: number;
    readonly ready: boolean;
    readonly status: string;
    readonly tags: string;
    readonly targetNodesSize: string;
}
