// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getLoadBalancer(args?: GetLoadBalancerArgs, opts?: pulumi.InvokeOptions): Promise<GetLoadBalancerResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("civo:index/getLoadBalancer:getLoadBalancer", {
        "hostname": args.hostname,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getLoadBalancer.
 */
export interface GetLoadBalancerArgs {
    /**
     * The hostname of the Load Balancer.
     */
    readonly hostname?: string;
    /**
     * The ID of the Load Balancer.
     */
    readonly id?: string;
}

/**
 * A collection of values returned by getLoadBalancer.
 */
export interface GetLoadBalancerResult {
    /**
     * A list of backend instances
     */
    readonly backends: outputs.GetLoadBalancerBackend[];
    /**
     * The wait time until the backend is marked as a failure
     */
    readonly failTimeout: number;
    /**
     * The path to check the health of the backend
     */
    readonly healthCheckPath: string;
    /**
     * The hostname of the Load Balancer
     */
    readonly hostname?: string;
    /**
     * The ID of the Load Balancer
     */
    readonly id?: string;
    /**
     * Should self-signed/invalid certificates be ignored from the backend servers
     */
    readonly ignoreInvalidBackendTls: boolean;
    /**
     * How many concurrent connections can each backend handle
     */
    readonly maxConns: number;
    /**
     * The max request size set in the configuration
     */
    readonly maxRequestSize: number;
    /**
     * The policy set in the Load Balancer
     */
    readonly policy: string;
    /**
     * The port set in the configuration.
     */
    readonly port: number;
    /**
     * The protocol used in the configuration.
     */
    readonly protocol: string;
    /**
     * If is set will be returned
     */
    readonly tlsCertificate: string;
    /**
     * If is set will be returned
     */
    readonly tlsKey: string;
}
