// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Retrieves information about the region that Civo supports, with the ability to filter the results.
 */
export function getRegion(args?: GetRegionArgs, opts?: pulumi.InvokeOptions): Promise<GetRegionResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("civo:index/getRegion:getRegion", {
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegion.
 */
export interface GetRegionArgs {
    filters?: inputs.GetRegionFilter[];
    sorts?: inputs.GetRegionSort[];
}

/**
 * A collection of values returned by getRegion.
 */
export interface GetRegionResult {
    readonly filters?: outputs.GetRegionFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly regions: outputs.GetRegionRegion[];
    readonly sorts?: outputs.GetRegionSort[];
}

export function getRegionOutput(args?: GetRegionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRegionResult> {
    return pulumi.output(args).apply(a => getRegion(a, opts))
}

/**
 * A collection of arguments for invoking getRegion.
 */
export interface GetRegionOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetRegionFilterArgs>[]>;
    sorts?: pulumi.Input<pulumi.Input<inputs.GetRegionSortArgs>[]>;
}
