// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getReservedIp(args?: GetReservedIpArgs, opts?: pulumi.InvokeOptions): Promise<GetReservedIpResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("civo:index/getReservedIp:getReservedIp", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getReservedIp.
 */
export interface GetReservedIpArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getReservedIp.
 */
export interface GetReservedIpResult {
    readonly id?: string;
    readonly instanceId: string;
    readonly instanceName: string;
    readonly ip: string;
    readonly name?: string;
    readonly region: string;
}

export function getReservedIpOutput(args?: GetReservedIpOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetReservedIpResult> {
    return pulumi.output(args).apply(a => getReservedIp(a, opts))
}

/**
 * A collection of arguments for invoking getReservedIp.
 */
export interface GetReservedIpOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
