name: Upload bin assets
description: Uploads the provider and tfgen binaries to `bin/`.

runs:
  using: "composite"
  steps:
    - name: Tar provider binaries
      shell: bash
      run: tar -zcf ${{ github.workspace }}/bin/provider.tar.gz -C ${{ github.workspace }}/bin/ pulumi-resource-civo pulumi-tfgen-civo
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: civo-provider.tar.gz
        path: ${{ github.workspace }}/bin/provider.tar.gz
        retention-days: 30
